# Generated by Django 5.2.7 on 2025-11-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_video_options_video_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='page',
            field=models.CharField(choices=[('page1', 'Страница 1'), ('page2', 'Страница 2'), ('internet_fraud', 'Интернет-мошенничество')], default='internet_fraud', max_length=20, verbose_name='Страница для отображения'),
        ),
    ]
